/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    teams: TeamAuthOperations;
  };
  blocks: {};
  collections: {
    projects: Project;
    teams: Team;
    tickets: Ticket;
    statuses: Status;
    milestones: Milestone;
    'field-definitions': FieldDefinition;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    tickets: TicketsSelect<false> | TicketsSelect<true>;
    statuses: StatusesSelect<false> | StatusesSelect<true>;
    milestones: MilestonesSelect<false> | MilestonesSelect<true>;
    'field-definitions': FieldDefinitionsSelect<false> | FieldDefinitionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: Team & {
    collection: 'teams';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface TeamAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Projects organize related tickets together
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  /**
   * The Team Member who created this. Empty for records written before actor tracking, or by an unauthenticated caller.
   */
  createdBy?: (string | null) | Team;
  /**
   * The Team Member who last changed this.
   */
  updatedBy?: (string | null) | Team;
  /**
   * The name of the project
   */
  name: string;
  /**
   * Short prefix for ticket IDs (e.g., PROJ for PROJ-123)
   */
  prefix: string;
  /**
   * Detailed description of the project
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Icon to represent the project
   */
  icon?:
    | (
        | 'folder'
        | 'rocket'
        | 'zap'
        | 'star'
        | 'heart'
        | 'flag'
        | 'target'
        | 'briefcase'
        | 'code'
        | 'box'
        | 'layers'
        | 'database'
        | 'megaphone'
        | 'cloud'
        | 'users'
      )
    | null;
  /**
   * Color theme for the project
   */
  color?:
    | (
        | '#6366f1'
        | '#8b5cf6'
        | '#a855f7'
        | '#d946ef'
        | '#ec4899'
        | '#ef4444'
        | '#f97316'
        | '#f59e0b'
        | '#eab308'
        | '#22c55e'
        | '#14b8a6'
        | '#06b6d4'
        | '#3b82f6'
      )
    | null;
  /**
   * Current status of the project
   */
  status: 'ACTIVE' | 'ON_HOLD' | 'COMPLETED' | 'CANCELLED';
  /**
   * Auto-incremented counter for ticket IDs
   */
  ticketCounter?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who do the work. Stored under the slug "teams" for compatibility — the concept is a person, not a group.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: string;
  /**
   * Display name, e.g. Kimberly Brody
   */
  name: string;
  /**
   * Up to 3 characters for compact avatars. Derived from the name when empty.
   */
  initials?: string | null;
  /**
   * admin can delete; member is an ordinary person; agent is an automated caller and should hold an API key rather than a password.
   */
  role: 'admin' | 'member' | 'agent';
  /**
   * Inactive members keep their history but drop out of assignment pickers
   */
  active?: boolean | null;
  color?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Individual work items within projects
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets".
 */
export interface Ticket {
  id: string;
  /**
   * Auto-generated ticket ID (e.g., PROJ-123)
   */
  ticketId?: string | null;
  /**
   * Brief title of the ticket
   */
  title: string;
  /**
   * Detailed description of the work
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The `key` of a row in the Statuses collection. This is deliberately a free string rather than a fixed list: workflow states are configurable per workspace.
   */
  status: string;
  /**
   * Priority level of the ticket
   */
  priority?: ('NO_PRIORITY' | 'URGENT' | 'HIGH' | 'MEDIUM' | 'LOW') | null;
  /**
   * The project this ticket belongs to
   */
  project: string | Project;
  /**
   * The Team Member responsible for this ticket
   */
  team?: (string | null) | Team;
  /**
   * Tickets that must be completed before this ticket can be worked on
   */
  blockedBy?: (string | Ticket)[] | null;
  /**
   * The dated marker this work is aimed at
   */
  milestone?: (string | null) | Milestone;
  /**
   * Labels for categorization
   */
  labels?:
    | {
        name: string;
        color?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * When work is planned to start. With a due date this draws a bar on the timeline; without one the ticket shows as a milestone diamond on its due date rather than a fabricated bar.
   */
  startDate?: string | null;
  /**
   * When this ticket should be completed
   */
  dueDate?: string | null;
  /**
   * Subtasks for this ticket
   */
  subtasks?:
    | {
        title: string;
        completed?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Values for the workspace-defined fields in the Custom Fields collection. Domain vocabulary lives here rather than in the schema.
   */
  customFields?:
    | {
        key: string;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The Team Member who created this. Empty for records written before actor tracking, or by an unauthenticated caller.
   */
  createdBy?: (string | null) | Team;
  /**
   * The Team Member who last changed this.
   */
  updatedBy?: (string | null) | Team;
  /**
   * Order within the column
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Dated markers work is planned against. Rendered as vertical lines on the timeline.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "milestones".
 */
export interface Milestone {
  id: string;
  name: string;
  date: string;
  color?: string | null;
  description?: string | null;
  /**
   * Leave empty for a milestone that applies across every project
   */
  project?: (string | null) | Project;
  updatedAt: string;
  createdAt: string;
}
/**
 * The workflow states this workspace uses. Board columns are built from these.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "statuses".
 */
export interface Status {
  id: string;
  /**
   * Stable machine value stored on tickets, e.g. IN_PROGRESS. Changing it after tickets exist orphans them — add a new status instead.
   */
  key: string;
  /**
   * Shown on the board column and the ticket
   */
  label: string;
  color?: string | null;
  /**
   * Left-to-right position on the board
   */
  order: number;
  /**
   * New tickets land here when no status is given. Exactly one status should have this set.
   */
  isDefault?: boolean | null;
  /**
   * Marks work as finished. Dependency logic reads this: a ticket is "ready" when every blocker sits in a done status.
   */
  isDone?: boolean | null;
  /**
   * Marks work as waiting on something. Used to distinguish waiting from not-started.
   */
  isBlocked?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Extra fields this workspace wants on its tickets.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "field-definitions".
 */
export interface FieldDefinition {
  id: string;
  /**
   * Stable machine value stored on tickets, e.g. voice_part
   */
  key: string;
  label: string;
  type: 'text' | 'number' | 'date' | 'select' | 'checkbox' | 'url';
  /**
   * Only used when type is Select
   */
  options?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave empty to apply this field to every project
   */
  project?: (string | null) | Project;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'teams';
        value: string | Team;
      } | null)
    | ({
        relationTo: 'tickets';
        value: string | Ticket;
      } | null)
    | ({
        relationTo: 'statuses';
        value: string | Status;
      } | null)
    | ({
        relationTo: 'milestones';
        value: string | Milestone;
      } | null)
    | ({
        relationTo: 'field-definitions';
        value: string | FieldDefinition;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'teams';
    value: string | Team;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'teams';
    value: string | Team;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  createdBy?: T;
  updatedBy?: T;
  name?: T;
  prefix?: T;
  description?: T;
  icon?: T;
  color?: T;
  status?: T;
  ticketCounter?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  name?: T;
  initials?: T;
  role?: T;
  active?: T;
  color?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets_select".
 */
export interface TicketsSelect<T extends boolean = true> {
  ticketId?: T;
  title?: T;
  description?: T;
  status?: T;
  priority?: T;
  project?: T;
  team?: T;
  blockedBy?: T;
  milestone?: T;
  labels?:
    | T
    | {
        name?: T;
        color?: T;
        id?: T;
      };
  startDate?: T;
  dueDate?: T;
  subtasks?:
    | T
    | {
        title?: T;
        completed?: T;
        id?: T;
      };
  customFields?:
    | T
    | {
        key?: T;
        value?: T;
        id?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "statuses_select".
 */
export interface StatusesSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  color?: T;
  order?: T;
  isDefault?: T;
  isDone?: T;
  isBlocked?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "milestones_select".
 */
export interface MilestonesSelect<T extends boolean = true> {
  name?: T;
  date?: T;
  color?: T;
  description?: T;
  project?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "field-definitions_select".
 */
export interface FieldDefinitionsSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  type?: T;
  options?:
    | T
    | {
        value?: T;
        id?: T;
      };
  project?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}